import Head from 'next/head'
import { useEffect, useState } from 'react'
import Button from '../components/Button'
import { signInWithGithub, onAuthStateChange } from '../firebase/client'


export default function Home() {
  const [user, setUser] = useState(null)

  useEffect(()=>{
    onAuthStateChange(setUser)
  }, [])

  const handleClick = () => {
    signInWithGithub().then(user => {
      const { avatar, nombre, mail } = user
      setUser(user)

    }).catch(err => {
      console.log(err)
    })

  }

  return (
    <div>
      <Head>
        <title className='font-sans'>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-100 grid place-items-center h-screen'>
        <main className='bg-white w-full max-w-lg h-full grid place-content-center place-items-center xs:w-11/12 xs:h-90v xs:rounded-lg xs:shadow-md'>
          <img src='/twitter.png' alt='imagen logo' className='w-20'></img>
          <h1 className="text-blue-600 rounded-lg text-sans">Devter!</h1>
          <h2 className="text-lg text-blue-800 rounded-lg text-sans">Talk about development with developers</h2>

          {
            user === null ?
              <Button onClick={handleClick}>
                <div className='flex flex-row items-center'>
                  <img src='/descarga.png' alt='imagen github' className='w-5 h-5 mr-2'></img>
                  Login with GitHub
                </div>
              </Button>
              :
              <div className='flex flex-row items-center'>
                <img src={user.avatar} className="w-10 h-10 mr-3"></img>
                <div>
                  <p>usuario: {user.nombre}</p>
                  <p>email: {user.mail}</p>
                </div>
              </div>
          }


        </main>
      </div>

    </div>
  )
}
